[tool.poetry]
name = "coinz-backend"
version = "0.1.0"
description = ""
authors = ["Eason Chang <eason@easonchang.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.12"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
