# Generated by Django 5.0.3 on 2024-03-19 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coinz_api', '0003_category_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='currencyconversion',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
