# Generated by Django 5.0.3 on 2024-03-23 20:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coinz_api', '0004_alter_currencyconversion_updated_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recurringbill',
            name='ledger',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recurring_bills', to='coinz_api.ledger'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='ledger',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='coinz_api.ledger'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='recurring_bill',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transactions', to='coinz_api.recurringbill'),
        ),
    ]
