# Generated by Django 5.0.3 on 2024-03-25 03:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coinz_api', '0007_rename_interval_days_recurringbill_interval_amount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='currency',
            name='precision',
            field=models.IntegerField(default=0),
        ),
    ]
