# Generated by Django 5.0.3 on 2024-03-25 03:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coinz_api', '0008_currency_precision'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersettings',
            name='display_currency',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='display_currency', to='coinz_api.currency'),
        ),
        migrations.AlterField(
            model_name='recurringbill',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recurring_bills', to='coinz_api.category'),
        ),
        migrations.AlterField(
            model_name='recurringbill',
            name='currency',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recurring_bills', to='coinz_api.currency'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transactions', to='coinz_api.category'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='currency',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='coinz_api.currency'),
        ),
        migrations.AlterField(
            model_name='usersettings',
            name='default_currency',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='default_currency', to='coinz_api.currency'),
        ),
    ]
